### ISSUE TITLE
E017.- Falta cambiar el idioma del hipervínculo "Home" en "Municipios"

### ISSUE THREAD

**Issue by Edgar1828** [masuareb/2017-01-isc-6to-palmicultores#17]
Falta cambiar el idioma del hipervínculo "Home" ubicado en "Municipios"
Pasos.-
1.- Acceder al Sistema
2.- Dar click en el hipervínculo "Municipios"
3.- Observar que el idioma del hipervínculo "Home" ubicado en la parte de arriba está en inglés; el cual debe ser cambiado a español.
![home_mu](https://cloud.githubusercontent.com/assets/26654857/24331920/eee29526-11fa-11e7-9b1d-de11346e28df.JPG)

**Comment by IgnacioHernandezNacho** [comment]
corregido


________________________________
De: Edgar1828 <notifications@github.com>
Enviado: domingo, 26 de marzo de 2017 07:54 a. m.
Para: masuareb/2017-01-isc-6to-palmicultores
Cc: Subscribed
Asunto: [masuareb/2017-01-isc-6to-palmicultores] E016.- Falta cambiar el idioma del botón "Search" en "Advanced Search" (#17)


Falta cambiar el idioma del botón "Search" a español, ubicado en "Advanced Search"
Pasos.-
1.- Acceder al Sistema
2.- Dar click en el hipervínculo "Localidades"
3.- Dar click en el hipervínculo "Buscar Localidad"
4.- Dar click en el hipervínculo "Advanced Search"
4.- Observar que el idioma del del botón "Search" está en inglés; el cual debe ser cambiado a español.
[boton]<https://cloud.githubusercontent.com/assets/26654857/24331835/64fb8a80-11f9-11e7-85e2-b42f96b11aae.JPG>

[https://cloud.githubusercontent.com/assets/26654857/24331835/64fb8a80-11f9-11e7-85e2-b42f96b11aae.JPG]
