### ISSUE TITLE
E018.- Falta corregir el título que aparece en el hipervínculo "Localidades"

### ISSUE THREAD

**Issue by Edgar1828** [masuareb/2017-01-isc-6to-palmicultores#18]
Falta corregir el título que se muestra en el hipervínculo "Localidades", es decir; cambiar el texto de "Localidades" a "Listado de Localidades"
Pasos.-
1.- Acceder al sistema.
2.- Dar click en el catálogo "Localidades".
3.- Observar que el titulo ubicado en "Localidades" no está escrito como debe de ser; por lo cual es necesario corregirlo cambiando el texto a "Listado de Localidades" como e muestra en "Municipios"
![titulos](https://cloud.githubusercontent.com/assets/26654857/24332064/2f8cffec-11fd-11e7-95db-37ea8ee37750.jpg)

**Comment by IgnacioHernandezNacho** [comment]
corregido


________________________________
De: Edgar1828 <notifications@github.com>
Enviado: domingo, 26 de marzo de 2017 08:21 a. m.
Para: masuareb/2017-01-isc-6to-palmicultores
Cc: Subscribed
Asunto: [masuareb/2017-01-isc-6to-palmicultores] E018.- Falta corregir el texto del hipervínculo "Localidades" (#18)


Falta corregir el título que se muestra en el hipervínculo "Localidades", es decir; cambiar el texto de "Localidades" a "Listado de Localidades"
Pasos.-
1.- Acceder al sistema.
2.- Dar click en el catálogo "Localidades".
3.- Observar que el titulo ubicado en "Localidades" no está escrito como debe de ser; por lo cual es necesario corregirlo cambiando el texto a "Listado de Localidades" como e muestra en "Municipios"
[titulos]<https://cloud.githubusercontent.com/assets/26654857/24332064/2f8cffec-11fd-11e7-95db-37ea8ee37750.jpg>

[https://cloud.githubusercontent.com/assets/26654857/24332064/2f8cffec-11fd-11e7-95db-37ea8ee37750.jpg]

**Comment by OscarMarroquin** [comment]
corregido

________________________________
De: Edgar1828 <notifications@github.com>
Enviado: domingo, 26 de marzo de 2017 08:21:30 a. m.
Para: masuareb/2017-01-isc-6to-palmicultores
Cc: Subscribed
Asunto: [masuareb/2017-01-isc-6to-palmicultores] E018.- Falta corregir el texto del hipervínculo "Localidades" (#18)


Falta corregir el título que se muestra en el hipervínculo "Localidades", es decir; cambiar el texto de "Localidades" a "Listado de Localidades"
Pasos.-
1.- Acceder al sistema.
2.- Dar click en el catálogo "Localidades".
3.- Observar que el titulo ubicado en "Localidades" no está escrito como debe de ser; por lo cual es necesario corregirlo cambiando el texto a "Listado de Localidades" como e muestra en "Municipios"
[titulos]<https://cloud.githubusercontent.com/assets/26654857/24332064/2f8cffec-11fd-11e7-95db-37ea8ee37750.jpg>
