### ISSUE TITLE
E024.- Falta cambiar el idioma del botón "Search" en "Advanced Search"

### ISSUE THREAD

**Issue by Edgar1828** [masuareb/2017-01-isc-6to-palmicultores#24]
Falta cambiar el idioma a español del botón "Search" que se encuentra ubicado en "Advanced Search"
Pasos.-
1.- Acceder al sistema.
2.- Dar click en el catálogo Municipios.
3.- Dar click en la operación "Buscar Municipio"
4.- Dar click en el hipervínvulo "Advanced Search"
5.- Observar que el botón "Search" está en inglés; por lo que debe ser cambiado al idioma español.
![search](https://cloud.githubusercontent.com/assets/26654857/24332481/78abb0b8-1204-11e7-8bb7-dd36319cc7d8.JPG)

**Comment by IgnacioHernandezNacho** [comment]
simon loco



________________________________
De: Edgar1828 <notifications@github.com>
Enviado: domingo, 26 de marzo de 2017 09:13 a. m.
Para: masuareb/2017-01-isc-6to-palmicultores
Cc: Subscribed
Asunto: [masuareb/2017-01-isc-6to-palmicultores] E024.- Falta cambiar el idioma del botón "Search" en "Advanced Search" (#24)


Falta cambiar el idioma a español del botón "Search" que se encuentra ubicado en "Advanced Search"
Pasos.-
1.- Acceder al sistema.
2.- Dar click en el catálogo Municipios.
3.- Dar click en la operación "Buscar Municipio"
4.- Dar click en el hipervínvulo "Advanced Search"
5.- Observar que el botón "Search" está en inglés; por lo que debe ser cambiado al idioma español.
[search]<https://cloud.githubusercontent.com/assets/26654857/24332481/78abb0b8-1204-11e7-8bb7-dd36319cc7d8.JPG>

[https://cloud.githubusercontent.com/assets/26654857/24332481/78abb0b8-1204-11e7-8bb7-dd36319cc7d8.JPG]

**Comment by IgnacioHernandezNacho** [comment]
corregido


________________________________
De: Edgar1828 <notifications@github.com>
Enviado: domingo, 26 de marzo de 2017 09:13 a. m.
Para: masuareb/2017-01-isc-6to-palmicultores
Cc: Subscribed
Asunto: [masuareb/2017-01-isc-6to-palmicultores] E024.- Falta cambiar el idioma del botón "Search" en "Advanced Search" (#24)


Falta cambiar el idioma a español del botón "Search" que se encuentra ubicado en "Advanced Search"
Pasos.-
1.- Acceder al sistema.
2.- Dar click en el catálogo Municipios.
3.- Dar click en la operación "Buscar Municipio"
4.- Dar click en el hipervínvulo "Advanced Search"
5.- Observar que el botón "Search" está en inglés; por lo que debe ser cambiado al idioma español.
[search]<https://cloud.githubusercontent.com/assets/26654857/24332481/78abb0b8-1204-11e7-8bb7-dd36319cc7d8.JPG>

[https://cloud.githubusercontent.com/assets/26654857/24332481/78abb0b8-1204-11e7-8bb7-dd36319cc7d8.JPG]
